### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by mithuncoder** [hahbiubiubiu/Python-Obfuscate#2]
with open('enc_func.py', 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'enc_func.py' in line 112

In your obfuscation missing file..
"""
    def visit_Module(self, node: Module) -> Module:
        with open('enc_func.py', 'r', encoding='utf-8') as f:
            enc_func = eval(f.read())
        node.body = enc_func + node.body
        node.body = [self.visit(child) for child in node.body]
        node.body = [node.body[2]] + self.attr_nodes + node.body[3:]
        node.body = self.import_nodes + self.var_nodes + node.body
        global hash2str_name
        hash2str_name = self.global_var['hash2str']
        return node
        
"""

Update your code. I saw the example output of the obfuscated code. This is the next level of obfuscation.

**Comment by hahbiubiubiu** [comment]
Sorry for forgetting to provide the necessary file.
The enc_func.py has been uploaded.
